### ISSUE TITLE
s2wasm has incorrect tableswitch output

### ISSUE THREAD

**Issue by binji** [WebAssembly/binaryen#70]
s2wasm outputs tableswitch using blocks instead of cases, see switch-1.c.wast in torture-tests:
```
                (block $BB1_13
                  (block $BB1_12
                    (block $BB1_11
                      (block $BB1_9
                        (block $BB1_7
                          (block $BB1_5
                            (tableswitch 
                              (get_local $$2)
                              (table (case $BB1_5) (case $BB1_14) (case $BB1_7) (case $BB1_14) (case $BB1_14) (case $BB1_9) (case $BB1_14) (case $BB1_11)) (case $BB1_5)
                            )
                          )
...
```

It looks like this may be changed soon in the spec repo, so maybe it's not worth fixing here, however.

**Comment by kripken** [comment]
Yes, still changing I think. But also, I think it's valid either way? The tableswitch could always branch to an enclosing block. So that code should be valid in the current spec.

**Comment by binji** [comment]
Right, but then it should be ``(table (br $BB1_5) ...`` to differentiate.

**Comment by kripken** [comment]
Oh right, thanks. Ok, this was actually a bug in the tableswitch logic in general. Fixed now.

**Comment by binji** [comment]
Looks like it is still broken for the default case:
```
          (block $BB1_6
            (block $BB1_5
              (block $BB1_4
                (block $BB1_3
                  (block $BB1_2
                    (tableswitch 
                      (get_local $$0)
                      (table (br $BB1_2) (br $BB1_3) (br $BB1_4) (br $BB1_5) (br $BB1_6)) (case $BB1_2)
                    )
                  )
```
(see 20011219-1.c.s.wast)

**Comment by kripken** [comment]
Oh right, thanks, the default is separate. Fixed now.
